/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 rock.gltf --transform
Author: skinny hands (https://sketchfab.com/skinnyhands)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stylized-rock-47f2a1d475684327a4b9447772690cde
Title: Stylized  rock
*/

import { Stage, OrbitControls } from "@react-three/drei";
import { Canvas } from "@react-three/fiber";
import React, { Suspense } from "react";

import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/img/rock-transformed.glb");
  return (
    <Canvas>
      <Suspense fallback={null}>
        <Stage environment="studio" intensity={0.6}>
          <group {...props} dispose={null}>
            <mesh
              geometry={nodes.Object_4.geometry}
              material={materials.low_1}
              rotation={[Math.PI / 2, 0, -2.581]}
              scale={0.215}
            />
          </group>
        </Stage>

        <OrbitControls enableZoom={false} />
      </Suspense>
    </Canvas>
  );
}

useGLTF.preload("/img/rock-transformed.glb");
