/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 shiba.gltf --transform
Author: zixisun02 (https://sketchfab.com/zixisun51)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/shiba-faef9fe5ace445e7b2989d1c1ece361c
Title: Shiba
*/

import { Stage, OrbitControls } from "@react-three/drei";
import { Canvas } from "@react-three/fiber";
import React, { Suspense } from "react";

import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/img/shiba-transformed.glb");
  return (
    <Canvas>
      <Suspense fallback={null}>
        <Stage environment="studio" intensity={0.6}>
          <group {...props} dispose={null}>
            <mesh
              geometry={nodes.Group18985_default_0.geometry}
              material={materials["default"]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
          </group>
        </Stage>

        <OrbitControls enableZoom={false} />
      </Suspense>
    </Canvas>
  );
}

useGLTF.preload("/img/shiba-transformed.glb");
