/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 tree.gltf --transform
Author: Andriy Shekh (https://sketchfab.com/sheh5262)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pine-tree-e52769d653cd4e52a4acff3041961e65
Title: Pine tree
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('../public/img/tree-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Leaves001_Leavs_0.geometry} material={materials.Leavs} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.Trank001_Trank_0.geometry} material={materials.Trank} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
    </group>
  )
}

useGLTF.preload('../public/img/tree-transformed.glb')
